[build]
  command = "npm run build && yarn install"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[dev]
  command = "vite"
  targetPort = 5173
  port = 8888
  framework = "vite"
